[Rule]
RULE-SET,https://raw.githubusercontent.com/ziojio/store/main/ruleset/Apple.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/ziojio/store/main/ruleset/China.list,DIRECT,no-resolve
RULE-SET,https://raw.githubusercontent.com/ziojio/store/main/ruleset/Microsoft.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/ziojio/store/main/ruleset/Direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/ziojio/store/main/ruleset/Proxy.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/telegramcidr.txt,PROXY
RULE-SET,https://raw.githubusercontent.com/ziojio/store/main/ruleset/Lan.list,DIRECT
GEOIP,CN,DIRECT
FINAL,PROXY